//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REVELLACLOTHING.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbrevellaEntities : DbContext
    {
        public dbrevellaEntities()
            : base("name=dbrevellaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcostumer> tblcostumers { get; set; }
        public virtual DbSet<tblitem> tblitems { get; set; }
        public virtual DbSet<tbladmin> tbladmins { get; set; }
    }
}
