//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REVELLACLOTHING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblitem
    {
        public int id { get; set; }
        public string uid { get; set; }
        public string category { get; set; }
        public string item { get; set; }
        public string status { get; set; }
        public string price { get; set; }
    }
}
